### ISSUE TITLE
LSC PIR vragen

### ISSUE THREAD

**Issue by DutchCoban** [DenDeze/LSC#1]
Ik heb zojuist de LSC PIR voorzien van Tasmota 8.1.0.9 en het viel mij op dat ik twee toggles kreeg in het hoofdmenu, kan iemand mij aangeven waarvoor deze zijn?

Ik heb deze unit direct vanuit de doos voorzien van Tasmota, ingesteld volgens de instructie terwijl deze aan de TTL-USB adapter hing (PL2303). Zodra hem echter voed via batterij en ik op het knopje druk kan ik hem met geen mogelijkheid bereiken. Iemand een idee wat ik mogelijk over het hoofd heb gezien?

**Comment by rikki78** [comment]
Same issue here!

**Comment by DutchCoban** [comment]
Ik moet wel opmerken dat het device wel een bericht naar Domoticz stuurt. Die minuut dat het device bereikbaar zou moeten zijn lukt hem echt niet.

**Comment by DenDeze** [comment]
Sorry voor de trage reactie, hebben jullie een mqtt broker in gebruik?

**Comment by DenDeze** [comment]
Van zodra dat de 3,3 v voeding er af gaat neemt de tuya chip weer de spanningstoevoer naar de esp over. Je krijgt alleen een power on en off status.

**Comment by DutchCoban** [comment]
> Sorry voor de trage reactie, hebben jullie een mqtt broker in gebruik?

Toch bedankt voor de reactie. In mijn geval gaan de berichten via MQTT.

**Comment by DenDeze** [comment]
Ikzelf heb hem niet meer kunnen bereiken na het flashen, ik heb wel mijn draden afgeknipt op 4 cm lengte om later weer aan te kunnen koppelen. Tasmota heeft net genoeg tijd wifi connectie te maken en een status door te geven.

**Comment by DenDeze** [comment]
Om opnieuw te flashen of instellingen aanpassen kan je het best de 3,3 volt weer aansluiten.
