### ISSUE TITLE
not work with this motion detector

### ISSUE THREAD

**Issue by Benoulimou** [DenDeze/LSC#2]
Hello 

Thank you for your tutorial, 
I bought a lsc motion detector slightly different from yours. 
I have managed to flash it but the commands I put in termite don't change anything. I have no detection and everything appears as buttons. 

Can you help me?

**Comment by DenDeze** [comment]
No sorry, without the hardware i can't help. Sorry for the late reply.

**Comment by DenDeze** [comment]
shelly devices are better than the lsc products at this moment.
